### ISSUE TITLE
pip prints the following errors:

### ISSUE THREAD

**Issue by pixelgaurav** [jlengstorf/tutorial-deploy-nodejs-ssl-digitalocean-app#27]
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.

Exception:
Traceback (most recent call last):
File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/pip/_internal/cli/base_command.py", line 176, in main
status = self.run(options, args)
File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 346, in run
session=session, autobuilding=True
File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/pip/_internal/wheel.py", line 848, in build
assert building_is_possible
AssertionError
getting above error on this command "./certbot-auto certonly --standalone"  @jlengstorf

**Comment by jlengstorf** [comment]
@pixelgaurav this looks like something outside the tutorial. Check [the pip docs](https://pip.pypa.io/en/stable/) for upgrade instructions.

Good luck!
